### ISSUE TITLE
Rocket Chat - Shibboleth configuration problem

### ISSUE THREAD

**Issue by tbellembois** [IdentityPython/SATOSA#205]
Hello,

I am trying to configure SATOSA in front of a Rocket Chat server to enable Shibboleth authentication because Rocket Chat does not support IDP discovery.

I am properly redirected to the Renater WAYF page but I have this error:
```The return URL 'https://authproxy.dsi.uca.fr/Saml2/disco' could not be verified for Service Provider 'https://rocket.dsi.uca.fr/_saml/metadata/uca'```

`https://rocket.dsi.uca.fr/_saml/metadata/uca` is declared as a SP in the Renater federation.

Here is my `proxy_conf.xml` file:
```
#--- SATOSA Config ---#
BASE: https://authproxy.dsi.uca.fr
INTERNAL_ATTRIBUTES: "internal_attributes.yaml"
COOKIE_STATE_NAME: "_saml_idp"
STATE_ENCRYPTION_KEY: "mysupersecurekey"
CUSTOM_PLUGIN_MODULE_PATHS:
  - "plugins/backends"
  - "plugins/frontends"
  - "plugins/micro_services"
BACKEND_MODULES:
  - "plugins/backends/saml2_backend.yaml"
FRONTEND_MODULES:
  - "plugins/frontends/saml2_frontend.yaml"
MICRO_SERVICES:
  - "plugins/microservices/static_attributes.yaml"
...
```
I can not figure out where I am wrong.

I have attached the SAML2 frontend and backend files and a screenshot of my rocket configuration.

If somebody that has successfully installed SATOSA for Rocket Chat could give me some sample configuration files this could help me.

Regards

![rocket](https://user-images.githubusercontent.com/18054222/53495719-ca04c780-3aa0-11e9-97d4-8a97f31b6f68.png)

[saml2_backend_yaml.txt](https://github.com/IdentityPython/SATOSA/files/2910579/saml2_backend_yaml.txt)
[saml2_frontend_yaml.txt](https://github.com/IdentityPython/SATOSA/files/2910580/saml2_frontend_yaml.txt)

**Comment by tbellembois** [comment]
A little update.
I can now select an IDP from the Renater test WAYF but I have an error after the authentication.

Here is the relevant log:
```
[2019-03-05 10:25:57] [DEBUG]: [urn:uuid:629cde76-44cd-4fea-bc21-864acd29fde9] Found existing common domain cookie Set-Cookie: _saml_idp=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AMXAqVdABmdyOMSiFGAh_ndOU_Yy_fhMQldub8B8RyogPxwNAoy_WdyLoLh4X1_UAXxMMGtK5hFOqs-c6SOCoJkSjwzdGJHb8ewjA5aSZ4nwWBMWG-...[troncated]

...

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
[2019-03-05 10:25:57] [ERROR]: Unknown error
Traceback (most recent call last):
  File "/opt/satosa/lib/python3.5/site-packages/satosa/base.py", line 286, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/base.py", line 228, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/backends/saml2.py", line 238, in authn_response
    return self.auth_callback_func(context, self._translate_response(authn_response, context.state))
  File "/opt/satosa/lib/python3.5/site-packages/satosa/base.py", line 197, in _auth_resp_callback_func
    context, internal_response)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/micro_services/attribute_modifications.py", line 17, in process
    return super().process(context, data)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/micro_services/base.py", line 33, in process
    return self.next(context, data)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/base.py", line 168, in _auth_resp_finish
    return frontend.handle_authn_response(context, internal_response)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/frontends/saml2.py", line 84, in handle_authn_response
    return self._handle_authn_response(context, internal_response, self.idp)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/frontends/saml2.py", line 381, in _handle_authn_response
    self._set_common_domain_cookie(internal_response, http_args, context)
  File "/opt/satosa/lib/python3.5/site-packages/satosa/frontends/saml2.py", line 462, in _set_common_domain_cookie
    idp_list = [urlsafe_b64decode(b64_idp).decode('utf-8') for b64_idp in b64_idp_list]
  File "/opt/satosa/lib/python3.5/site-packages/satosa/frontends/saml2.py", line 462, in <listcomp>
    idp_list = [urlsafe_b64decode(b64_idp).decode('utf-8') for b64_idp in b64_idp_list]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```

I can not figure out where is my mistake. Any clue will be appreciated.

Regards

**Comment by c00kiemon5ter** [comment]
Hello, this is an error while trying to convert from bytes to utf-8 string. I am not sure why that occurs but, I am guessing that you do not need the `common_domain_cookie` functionality at all.
You can simply remove the `common_domain_cookie` configuration options from `plugins/frontends/saml2_frontend.yaml` and give it a go.

**Comment by tbellembois** [comment]
Thanks ! That solves my problem.
I still have an error but this is now on the Rocket side.
Regards.
