### ISSUE TITLE
Rocket Chat - Error: SAML Profile did not contain an email address

### ISSUE THREAD

**Issue by tbellembois** [IdentityPython/SATOSA#209]
Hello,

I have a working SATOSA installation whth Shibboleth authentication.
Here are the returned attributes:
```
[2019-04-02 07:11:00] [DEBUG]: [urn:uuid:893ce3ff-b539-400e-a7cc-2a7d7ca34086] backend received attributes:
{
    "displayName": [
        "Thomas BELLEMBOIS"
    ],
    "cn": [
        "BELLEMBOIS Thomas"
    ],
    "eduPersonAffiliation": [
        "member",
        "employee"
    ],
    "mail": [
        "Thomas.BELLEMBOIS@uca.fr"
    ]
}
[2019-04-02 07:11:00] [DEBUG]: [urn:uuid:893ce3ff-b539-400e-a7cc-2a7d7ca34086] Routing to frontend: Saml2IDP 
[2019-04-02 07:11:00] [DEBUG]: [urn:uuid:893ce3ff-b539-400e-a7cc-2a7d7ca34086] Filter: ['displayname', 'givenname', 'mail', 'edupersontargetedid', 'surname', 'name']
[2019-04-02 07:11:00] [DEBUG]: frontend attribute displayName mapped from displayname
[2019-04-02 07:11:00] [DEBUG]: frontend attribute cn mapped from name
[2019-04-02 07:11:00] [DEBUG]: frontend attribute email mapped from mail
[2019-04-02 07:11:00] [DEBUG]: [urn:uuid:893ce3ff-b539-400e-a7cc-2a7d7ca34086] returning attributes {"displayName": ["Thomas BELLEMBOIS"], "email": ["Thomas.BELLEMBOIS@uca.fr"], "cn": ["BELLEMBOIS Thomas"]}
```
The `email` attribute is mapped from `mail`.
But Rocket can not "see" the `email` attribute:
```
[34mI20190402-09:11:01.413(2) RESULT :{"profile":{"inResponseToId":"id-4CAPqkYEprh6abRkF","issuer":"https://authproxy.dsi.uca.fr/Saml2IDP/proxy.xml","nameID":"Thomas.BELLEMBOIS@uca.fr","nameIDFormat":"urn:oasis:names:tc:SAML:2.0:nameid-format:transient","sessionIndex":"id-bzJNdqp8I3tsqQpiE","urn:oid:2-16-840-1-113730-3-1-241":"Thomas BELLEMBOIS","urn:oid:1-2-840-113549-1-9-1-1":"Thomas.BELLEMBOIS@uca.fr","urn:oid:2-5-4-3":"BELLEMBOIS Thomas"}} 
[34mI20190402-09:11:01.416(2) Exception while invoking method 'login' Error: SAML Profile did not contain an email address     at MethodInvocation.<anonymous> (packages/steffo:meteor-accounts-saml/server/saml_server.js:174:9)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (packages/rocketchat:lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
```
Not sure this is a SATOSA issue.
Thanks for your help.
Thomas

**Comment by c00kiemon5ter** [comment]
Hello, I think the attribute you want is not `email` but `mail` - ie, I believe the other side expects [`OID:0.9.2342.19200300.100.1.3`](http://software.internet2.edu/eduperson/internet2-mace-dir-eduperson-201310.html#mail)

Change that in `internal_attributes.yaml` and try it. 

```
attributes:
[...]
  mail:
    saml: [mail]
[...]
```

Otherwise, we must know what attribute is expected as the "email address".

PS: you can also see the resulting authn-response by using a saml tracer (SAML Chrome Panel, Firefox SAML-tracer, etc)

**Comment by tbellembois** [comment]
Thanks ! That solves my issue. I can now authenticate on Rocket Chat.
Thanks a lot for the quick answer.

**Comment by c00kiemon5ter** [comment]
That's great; and sorry for taking so long to answer your initial question while it was a simple one.
