### ISSUE TITLE
get_force_authn in saml2 backend does not work for some XSD boolean values

### ISSUE THREAD

**Issue by skoranda** [IdentityPython/SATOSA#247]
The `get_force_authn()` function in `backends/saml2.py` uses a comparison that does not work when the XSD boolean value for the `forceAuthn` attribute in a SAML authentication request is a numeric `1` or `0` instead of "true" or "false.

The comparison

```
is_set = str(from_state or from_context or from_config).lower() == "true"
```
will never end up with is_set = True if for example from_context is 1, since str(1) == "true" will never be true.

A secondary issue is that when get_force_authn() returns python False the False ends up being passed to pysaml2 client_base.py and then entity.py and that throws
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1078, in _escape_attrib
    if "&" in text:
TypeError: argument of type 'bool' is not iterable
```

## Code Version

Head of SATOSA master, commit f7bb955761edc36a0f722695537c9a6617d97329.

## Expected Behavior

Setting mirror_force_authn to true for the SAML backend configuration and sending in a SAML authn request with attribute forceAuthn set to the value `1` should result in the authn request sent to the authenticating IdP having forceAuthn set to a true XSD boolean.

## Current Behavior

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1078, in _escape_attrib
    if "&" in text:
TypeError: argument of type 'bool' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 981, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 831, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 568, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
  File "/opt/pysaml/saml2/__init__.py", line 707, in __str__
    x = self.to_string()
  File "/opt/pysaml/saml2/__init__.py", line 703, in to_string
    return ElementTree.tostring(self._to_element_tree(), encoding="UTF-8")
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1134, in tostring
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 775, in write
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1101, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1056, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize False (type bool)
Call stack:
  File "/usr/local/bin/gunicorn", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 30, in accept
    self.handle(listener, client, addr)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/satosa/satosa/proxy_server.py", line 71, in __call__
    data = self.app(environ, start_response)
  File "/opt/satosa/satosa/proxy_server.py", line 113, in __call__
    resp = self.run(context)
  File "/opt/satosa/satosa/base.py", line 287, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/opt/satosa/satosa/base.py", line 229, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/satosa/backends/saml2.py", line 365, in disco_response
    return self.authn_request(context, entity_id)
  File "/opt/satosa/satosa/backends/saml2.py", line 281, in authn_request
    destination, binding=response_binding, **kwargs)
  File "/opt/pysaml/saml2/client_base.py", line 471, in create_authn_request
    sign_alg=sign_alg, digest_alg=digest_alg, **args)
  File "/opt/pysaml/saml2/entity.py", line 495, in _message
    logger.info("REQUEST: %s", req)
Message: 'REQUEST: %s'
Arguments: (<saml2.samlp.AuthnRequest object at 0x7f1023410470>,)
[2019-06-26 12:40:41,793] [DEBUG] [satosa.backends.saml2]: [urn:uuid:17e5e665-24cd-4aaf-82ab-10ad1416e8a7] Failed to construct the AuthnRequest for state
Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1078, in _escape_attrib
    if "&" in text:
TypeError: argument of type 'bool' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/satosa/satosa/backends/saml2.py", line 283, in authn_request
    ht_args = self.sp.apply_binding(binding, "%s" % req, destination, relay_state=relay_state)
  File "/opt/pysaml/saml2/__init__.py", line 707, in __str__
    x = self.to_string()
  File "/opt/pysaml/saml2/__init__.py", line 703, in to_string
    return ElementTree.tostring(self._to_element_tree(), encoding="UTF-8")
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1134, in tostring
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 775, in write
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1101, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1056, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize False (type bool)
[2019-06-26 12:40:41,794] [ERROR] [satosa.base]: [urn:uuid:17e5e665-24cd-4aaf-82ab-10ad1416e8a7] ERROR_ID [urn:uuid:f88d339b-e782-41ca-84a7-1fe7863af7f2]
STATE:
{
    "force_authn": false,
    "ROUTER": "Saml2IDP",
    "SATOSA_BASE": {
        "requester": "https://sp-test.scgvm.net/sp/shibboleth"
    },
    "Saml2IDP": {
        "resp_args": {
            "destination": "https://sp-test.scgvm.net/Shibboleth.sso/SAML2/POST",
            "in_response_to": "_67f1c4f29148447f881f48a6f48224d0",
            "sp_entity_id": "https://sp-test.scgvm.net/sp/shibboleth",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
            "name_id_policy": "<ns0:NameIDPolicy xmlns:ns0=\"urn:oasis:names:tc:SAML:2.0:protocol\" AllowCreate=\"1\" />"
        },
        "relay_state": "ss:mem:bc274e2b493c16b274a4cc9189e1c0fb0d1245631a8fa5a923ad855213375a3e"
    },
    "CONSENT": {
        "filter": [
            "displayname",
            "organization",
            "name",
            "awsrole",
            "idpdisplayname",
            "uid",
            "schachomeorganization",
            "commonname",
            "schachomeorganizationtype",
            "employeenumber",
            "awsrolesessionname",
            "surname",
            "friendlycountryname",
            "emailaddress",
            "role",
            "edupersontargetedid",
            "idporgname",
            "noreduorgacronym",
            "upn",
            "mail",
            "awssessionduration",
            "givenname",
            "eppn",
            "ismemberof",
            "idporgdisplayname",
            "countryname"
        ],
        "requester_name": [
            {
                "text": "NIAID ICER test SP",
                "__class__": "urn:oasis:names:tc:SAML:metadata:ui&DisplayName",
                "lang": "en"
            }
        ]
    },
    "SESSION_ID": "urn:uuid:17e5e665-24cd-4aaf-82ab-10ad1416e8a7"
}
Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1078, in _escape_attrib
    if "&" in text:
TypeError: argument of type 'bool' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/satosa/satosa/backends/saml2.py", line 283, in authn_request
    ht_args = self.sp.apply_binding(binding, "%s" % req, destination, relay_state=relay_state)
  File "/opt/pysaml/saml2/__init__.py", line 707, in __str__
    x = self.to_string()
  File "/opt/pysaml/saml2/__init__.py", line 703, in to_string
    return ElementTree.tostring(self._to_element_tree(), encoding="UTF-8")
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1134, in tostring
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 775, in write
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1101, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1056, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize False (type bool)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/satosa/satosa/base.py", line 229, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/satosa/backends/saml2.py", line 365, in disco_response
    return self.authn_request(context, entity_id)
  File "/opt/satosa/satosa/backends/saml2.py", line 288, in authn_request
    raise SATOSAAuthenticationError(context.state, "Failed to construct the AuthnRequest") from exc
satosa.exception.SATOSAAuthenticationError: Failed to construct the AuthnRequest
```

## Steps to Reproduce
Set mirror_force_authn to true on the SAML backend and then send in an authentication request from a Shibboleth SP configured to force re-authentication. The authn request will look like

```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    AssertionConsumerServiceURL="https://sp-test.scgvm.net/Shibboleth.sso/SAML2/POST"
                    Destination="https://proxy-dev.sphericalcowgroup.com/Saml2/sso/redirect"
                    ForceAuthn="1"
                    ID="_67f1c4f29148447f881f48a6f48224d0"
                    IssueInstant="2019-06-26T12:40:39Z"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    Version="2.0"
                    > <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://sp-test.scgvm.net/sp/shibboleth</saml:Issuer> <samlp:NameIDPolicy AllowCreate="1" /> </samlp:AuthnRequest>
```

**Comment by c00kiemon5ter** [comment]
Fixed by efc709590977a52164f3ccf67aee45b63e4f6008

> The ForceAuthn value as delivered by the AuthnRequest to the frontend is
> an xsd:boolean value and can have the values:
> - "true"
> - "false"
> - "1" (true)
> - "0" (false)
> 
> When checking the value, we must take into account all values.
